CREATE TABLE `table` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`capacity` INT NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`deleted_at` DATETIME,
	PRIMARY KEY(`id`)
);
CREATE TABLE `reservation` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`table_reservation_id` INT NOT NULL,
	`user_id` INT NOT NULL,
	`no_of_people` INT NOT NULL,
	`occasion` VARCHAR(100),
	`special_request` VARCHAR(512),
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`deleted_at` DATETIME,
	PRIMARY KEY(`id`)
);
CREATE TABLE `table_reservation` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`table_id` INT NOT NULL,
	`starts_at` DATETIME NOT NULL,
	`ends_at` DATETIME,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`deleted_at` DATETIME,
	PRIMARY KEY(`id`)
);
CREATE TABLE `user` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`first_name` VARCHAR(100) NOT NULL,
	`last_name` VARCHAR(100) NOT NULL,
	`email` VARCHAR(512) NOT NULL UNIQUE,
	`password` VARCHAR(512) NOT NULL,
	`contact_number` VARCHAR(20) NOT NULL,
	`user_role` ENUM('CUSTOMER', 'ADMIN', 'STAFF') NOT NULL DEFAULT 'CUSTOMER',
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`deleted_at` DATETIME,
	PRIMARY KEY(`id`)
);
CREATE TABLE `menu_item` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`name` VARCHAR(255) NOT NULL,
	`description` VARCHAR(1024) NOT NULL,
	`price` DECIMAL(10, 2) NOT NULL,
	`category` ENUM(
		'APPETIZER',
		'DESSERT',
		'MAIN_COURSE',
		'SIDE_DISH'
	) NOT NULL,
	`cuisine_id` INT NOT NULL,
	`type` ENUM('MEAL', 'BEVERAGE', 'SPECIAL') NOT NULL,
	`image` VARCHAR(512) NOT NULL,
	`menu_id` INT NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`deleted_at` DATETIME,
	PRIMARY KEY(`id`)
);
CREATE TABLE `menu` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`name` VARCHAR(255) NOT NULL,
	`description` VARCHAR(1024) NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`deleted_at` DATETIME,
	PRIMARY KEY(`id`)
);
CREATE TABLE `cuisine` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`name` VARCHAR(255) NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`deleted_at` DATETIME,
	PRIMARY KEY(`id`)
);
CREATE TABLE `cart` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`user_id` INT NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`deleted_at` DATETIME,
	PRIMARY KEY(`id`)
);
CREATE TABLE `cart_item` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`cart_id` INT NOT NULL,
	`menu_item_id` INT NOT NULL,
	`quantity` INT NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`deleted_at` DATETIME,
	PRIMARY KEY(`id`)
);
CREATE TABLE `order` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`user_id` INT NOT NULL,
	`total_amount` DECIMAL(10, 2) NOT NULL,
	`status` ENUM('PENDING', 'COMPLETED', 'CANCELLED') NOT NULL,
	`reservation_id` INTEGER,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`deleted_at` DATETIME,
	PRIMARY KEY(`id`)
);
CREATE TABLE `order_item` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`order_id` INT NOT NULL,
	`menu_item_id` INT NOT NULL,
	`quantity` INT NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`deleted_at` DATETIME,
	PRIMARY KEY(`id`)
);
ALTER TABLE `reservation`
ADD FOREIGN KEY(`table_reservation_id`) REFERENCES `table_reservation`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `table_reservation`
ADD FOREIGN KEY(`table_id`) REFERENCES `table`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `reservation`
ADD FOREIGN KEY(`user_id`) REFERENCES `user`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `menu_item`
ADD FOREIGN KEY(`menu_id`) REFERENCES `menu`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `menu_item`
ADD FOREIGN KEY(`cuisine_id`) REFERENCES `cuisine`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `cart_item`
ADD FOREIGN KEY(`cart_id`) REFERENCES `cart`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `cart`
ADD FOREIGN KEY(`user_id`) REFERENCES `user`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `order`
ADD FOREIGN KEY(`user_id`) REFERENCES `user`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `order_item`
ADD FOREIGN KEY(`order_id`) REFERENCES `order`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `order_item`
ADD FOREIGN KEY(`menu_item_id`) REFERENCES `menu_item`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `order`
ADD FOREIGN KEY(`reservation_id`) REFERENCES `reservation`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;
