CREATE TABLE IF NOT EXISTS `table` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`capacity` INTEGER NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`deleted_at` DATETIME,
	PRIMARY KEY(`id`)
);
CREATE TABLE IF NOT EXISTS `reservation` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`table_reservation_id` INTEGER NOT NULL,
	`user_id` INTEGER NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`deleted_at` DATETIME,
	PRIMARY KEY(`id`)
);
CREATE TABLE IF NOT EXISTS `table_reservation` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`table_id` INTEGER NOT NULL,
	`starts_at` DATETIME NOT NULL,
	`ends_at` DATETIME,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`deleted_at` DATETIME,
	PRIMARY KEY(`id`)
);
CREATE TABLE IF NOT EXISTS `user` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`first_name` VARCHAR(100) NOT NULL,
	`last_name` VARCHAR(100) NOT NULL,
	`email` VARCHAR(100) NOT NULL UNIQUE,
	`contact_number` VARCHAR(100) NOT NULL UNIQUE,
	`password` VARCHAR(100) NOT NULL,
	`user_role` ENUM('CUSTOMER', 'ADMIN', 'STAFF') NOT NULL DEFAULT 'CUSTOMER',
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`deleted_at` DATETIME,
	PRIMARY KEY(`id`)
);
CREATE TABLE IF NOT EXISTS `menu_item` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`name` VARCHAR(100) NOT NULL,
	`description` VARCHAR(100) NOT NULL,
	`price` DECIMAL NOT NULL,
	`category` ENUM('APPETIZER', 'DESERT', 'MAIN_COURSE') NOT NULL,
	`cuisine_id` INTEGER NOT NULL,
	`type` ENUM('MEAL', 'BEVERAGE', 'SPECIAL') NOT NULL,
	`image` VARCHAR(100) NOT NULL,
	`menu_id` INTEGER NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`deleted_at` DATETIME,
	PRIMARY KEY(`id`)
);
CREATE TABLE IF NOT EXISTS `menu` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`name` VARCHAR(100) NOT NULL,
	`description` VARCHAR(100) NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`deleted_at` DATETIME,
	PRIMARY KEY(`id`)
);
CREATE TABLE IF NOT EXISTS `cuisine` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`name` VARCHAR(100) NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`deleted_at` DATETIME,
	PRIMARY KEY(`id`)
);
ALTER TABLE `reservation`
ADD FOREIGN KEY(`table_reservation_id`) REFERENCES `table_reservation`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `table_reservation`
ADD FOREIGN KEY(`table_id`) REFERENCES `table`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `reservation`
ADD FOREIGN KEY(`user_id`) REFERENCES `user`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `menu_item`
ADD FOREIGN KEY(`menu_id`) REFERENCES `menu`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `cuisine`
ADD FOREIGN KEY(`id`) REFERENCES `menu_item`(`cuisine_id`) ON UPDATE NO ACTION ON DELETE NO ACTION;
